INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Iron Man Cosplay', 'Cosplay', 99.99, 20);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Black Tie Suit', 'Formal', 149.99, 15);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Wonder Woman Cosplay', 'Cosplay', 89.99, 25);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Evening Gown', 'Formal', 199.99, 10);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Batman Cosplay', 'Cosplay', 79.99, 30);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Tuxedo', 'Formal', 129.99, 18);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Elsa Cosplay', 'Cosplay', 69.99, 22);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Cocktail Dress', 'Formal', 179.99, 12);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Spider-Man Cosplay', 'Cosplay', 84.99, 28);
INSERT INTO `Costumes` (`CostumeName`, `CostumeCategory`, `CostumePrice`, `CostumeStock`) VALUES ('Classic Suit', 'Formal', 159.99, 16);